---
- hosts: local
  roles:
    - ping
    - role: setup
      tags:
        - setup
        - install
    - role: gpg
      tags:
        - gpg
    - role: seekret
      tags:
        - setup
        - seekret
