---
- hosts: local
  roles:
    - ping
    - role: install
      tags:
        - setup
        - install
    - role: gpg
      tags:
        - gpg
    - role: caulking
      tags:
        - setup
        - caulking
