---
- name: get github release
  github_release:
    user: 18F
    repo: git-seekret
    action: latest_release
  register: release

- name: create working temp directory for seekret install
  tempfile:
    state: directory
    suffix: seekret-temp
  register: temp_directory

- name: temporary destination directory
  debug:
    var: temp_directory

- name: grab the 18F seekrets release
  get_url:
    dest: "{{ temp_directory.path }}"
    url: "https://github.com/18F/git-seekret/releases/download/{{ release.tag }}/git-seekret-osx"

- name: move git-seekret to /usr/local/bin
  copy:
    become: yes
    src: "{{ temp_directory.path }}/git-seekret-osx"
    dest: "/usr/local/bin/git-seekret"

- name: create a destination directory for rules
  file:
    path: "{{ lookup('env', 'HOME') }}/.git-support/seekret-rules"
    state: directory
  register: _rules_directory

- name: copy seekret rules
  copy:
    src: "{{ item }}"
    dest: "{{ _rules_directory.path }}"
  with_fileglob: "{{ role_path }}/files/*.rule"

- name: create a git-seekret hooks path
  file:
    path: "{{ lookup('env', 'HOME') }}/.git-support/hooks"
    state: directory

- name: create hooks directory for git-seekret
  command:
    cmd: git config --global core.hooksPath "{{ lookup('env', 'HOME') }}/.git-support/hooks"

- name: init the global seekret config
  command:
    cmd: git seekret --global config --init

- name: activate all the installed rules
  command:
    cmd: git seekret --global rules --enable-all

- name: activate all the installed hooks
  command:
    cmd: git seekret --global hook --enable-all
