---

# GPG for signing commits is annoying on macOS.
# https://stackoverflow.com/questions/39494631/gpg-failed-to-sign-the-data-fatal-failed-to-write-commit-object-git-2-10-0

# gnupg is also known as gnupg2, gpg, gpg2, and
# several other aliases in brew.
- name: install gpg
  homebrew:
    name: gnupg
    state: latest

- name: force gpg to be upgraded
  command: 
    cmd: brew upgrade gnupg

- name: tell brew to overwrite links for gnupg
  command: 
    cmd: brew link --overwrite gnupg

- name: install pinentry to support signing
  homebrew:
    name: pinentry-mac
    state: latest

- name: setup pinentry to support gnupg
  lineinfile:
    path: ~/.gnupg/gpg-agent.conf
    line: pinentry-program /usr/local/bin/pinentry-mac
    state: present
    create: yes

- name: kick the agent; we'll be using pinetry
  command:
    cmd: killall gpg-agent
